name: Update Trade Feed

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret Presence
        run: |
          if [ -n "${{ secrets.APPS_SCRIPT_URL }}" ]; then
            echo "APPS_SCRIPT_URL FOUND"
          else
            echo "APPS_SCRIPT_URL MISSING"
          fi

          if [ -n "${{ secrets.API_TOKEN }}" ]; then
            echo "API_TOKEN FOUND"
          else
            echo "API_TOKEN MISSING"
          fi
